INSERT INTO customer (FIRST_NAME,LAST_NAME,STATE) VALUES ('Jean', 'Feliz','S');
INSERT INTO customer (FIRST_NAME,LAST_NAME,STATE) VALUES ('Carlos', 'Ruiz','S');
INSERT INTO customer (FIRST_NAME,LAST_NAME,STATE) VALUES ('Angomas', 'DIGES','S');

INSERT INTO address (CUSTOMER_ID,ADDRESS,COUNTRY,ADDRESS_TYPE,STATE) VALUES (1, 'Direccion 1','Republica Dominicana','Comercial','S');
INSERT INTO address (CUSTOMER_ID,ADDRESS,COUNTRY,ADDRESS_TYPE,STATE) VALUES (2, 'Direccion 2','USA','Comercial','S');
INSERT INTO address (CUSTOMER_ID,ADDRESS,COUNTRY,ADDRESS_TYPE,STATE) VALUES (3, 'Direccion 3','Republica Dominicana','Comercial','S');