
DROP TABLE address IF EXISTS;
DROP TABLE customer IF EXISTS;

CREATE TABLE customer(
	CUSTOMER_ID INTEGER NOT NULL AUTO_INCREMENT,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
    STATE CHAR DEFAULT 'N',
	PRIMARY KEY  (CUSTOMER_ID)
);

--DROP TABLE address IF EXISTS;

CREATE TABLE address (
	ADDRESS_ID INTEGER NOT NULL AUTO_INCREMENT,
    CUSTOMER_ID INTEGER NOT NULL,
	DESCRIPTION VARCHAR(50)  NOT NULL,
    COUNTRY VARCHAR(50)  NOT NULL,
    ADDRESS_TYPE VARCHAR(50) NOT NULL,
    STATE CHAR DEFAULT 'N',
    PRIMARY KEY(ADDRESS_ID),
    CONSTRAINT FK_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES customer(CUSTOMER_ID)
);


